---
- name: Install SSH Server
  package:
    state: latest
    name:
      - openssh-server

- name: Disable root ssh password login
  lineinfile:
    state: present
    destfile: '/etc/ssh/sshd_config'
    regexp: '^#?PermitRootLogin\s'
    line: 'PermitRootLogin prohibit-password'
  notify: restart sshd
