---
- name: install required packages
  package:
    state: latest
    name:
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip

- name: Add an Apt signing key for docker repo
  apt_key:
    state: present
    id: 0EBFCD88
    url: https://download.docker.com/linux/debian/gpg

- apt_repository:
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename|lower }} stable
    update_cache: yes

- name: Install Docker-CE
  package:
    state: latest
    name:
      -  docker-ce

- name: Start Docker Service
  service:
    state: started
    enabled: true
    name: docker

- name: Create docker directory if it does not exist
  file:
    state: directory
    path: /srv/docker
    mode: '0750'
    owner: root
    group: root

- name: Install Docker-Compose
  pip:
    state: latest
    executable: pip3
    name:
      - docker-compose
